/**
 * Demo PDF download for invoice rows until API is wired.
 * @param {{ id?: string, client?: string, projectName?: string }} row
 */
export function downloadInvoicePdf(row) {
  const id = row?.id ?? "invoice";
  const client = row?.client ?? "Client";
  const project = row?.projectName ?? "Project";
  const lines = [
    "INVOICE",
    `ID: ${id}`,
    `Client: ${client}`,
    `Project: ${project}`,
    "",
    "Generated by Spade Community Admin",
  ];
  const blob = new Blob([lines.join("\n")], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `invoice-${String(id).replace(/\s+/g, "-")}.pdf`;
  link.click();
  URL.revokeObjectURL(url);
}
