import {
  matchesPrescreenMain,
  matchesSurveyMain,
  matchesCommunityUsersMain,
  matchesUserScreeningQuestionsMain,
  matchesPanelSurveyMain,
} from "./sidebarNavUtils";

export const SIDEBAR_NAV_ITEMS = [
  {
    type: "link",
    label: "Dashboard",
    root: "/",
    matcher: /^\/($|dashboard)/,
    permissionKeys: ["dashboard"],
  },
  {
    type: "link",
    label: "Admin Users",
    root: "/users",
    matcher: /^\/users(\/|$)/,
    permissionKeys: ["users"],
  },
  {
    type: "link",
    label: "Clients",
    root: "/clients",
    matcher: /^\/clients(\/|$)/,
    permissionKeys: ["clients"],
  },
  {
    type: "link",
    label: "Partners",
    root: "/partners",
    matcher: /^\/partners(\/|$)/,
    permissionKeys: ["partners"],
  },
  {
    type: "link",
    label: "Project Managers",
    root: "/project-managers",
    matcher: /^\/project-managers(\/|$)/,
    permissionKeys: ["project_managers"],
  },
  {
    type: "link",
    label: "Sales Manager",
    root: "/sales/sales-manager",
    matcher: /^\/sales\/sales-manager(\/|$)/,
    permissionKeys: ["sales_manager"],
  },
  {
    type: "link",
    label: "RFQ",
    root: "/sales/rfq",
    matcher: /^\/sales\/rfq(\/|$)/,
    permissionKeys: ["rfq"],
  },
  {
    type: "group",
    label: "Screening Management",
    key: "screening-management",
    matcher: /^\/prescreen(\/|$)/,
    permissionKeys: ["prescreen", "prescreen_group"],
    children: [
      {
        label: "Question Library",
        root: "/prescreen",
        isActive: matchesPrescreenMain,
        matcher: /^\/prescreen(\/|$)/,
        permissionKeys: ["prescreen"],
      },
      {
        label: "Questionnaire Group",
        root: "/prescreen/group",
        matcher: /^\/prescreen\/group(\/|$)/,
        permissionKeys: ["prescreen_group"],
      },
      // Hidden from navigation — kept for future use
      // {
      //   label: "Question Library",
      //   root: "/user-screening/questions",
      //   matcher: /^\/user-screening\/questions(\/|$)/,
      //   permissionKeys: ["user_screening_management"],
      // },
      // {
      //   label: "Create Survey",
      //   root: "/user-screening/create-survey",
      //   matcher: /^\/user-screening\/create-survey(\/|$)/,
      //   permissionKeys: ["user_screening_management"],
      // },
    ],
  },
  {
    type: "group",
    label: "Survey",
    key: "survey",
    matcher: /^\/survey(\/|$)/,
    permissionKeys: [
      "survey",
      "group_survey",
      "recontact_survey",
      "survey_settings",
    ],
    children: [
      {
        label: "Survey",
        root: "/survey",
        isActive: matchesSurveyMain,
        matcher: /^\/survey(\/|$)/,
        permissionKeys: ["survey"],
      },
      {
        label: "Group Survey",
        root: "/survey/group",
        matcher: /^\/survey\/group(\/|$)/,
        permissionKeys: ["group_survey"],
      },
      {
        label: "Recontact Survey",
        root: "/survey/recontact",
        matcher: /^\/survey\/recontact(\/|$)/,
        permissionKeys: ["recontact_survey"],
      },
      {
        label: "Survey Settings",
        root: "/survey/settings",
        matcher: /^\/survey\/settings(\/|$)/,
        permissionKeys: ["survey_settings"],
      },
    ],
  },
  {
    type: "group",
    label: "Invoice",
    key: "invoice",
    matcher: /^\/invoice(\/|$)/,
    permissionKeys: ["invoice", "invoice_settings", "invoices"],
    children: [
      {
        label: "Invoice Settings",
        root: "/invoice/settings",
        matcher: /^\/invoice\/settings(\/|$)/,
        permissionKeys: ["invoice_settings"],
      },
      {
        label: "Invoices",
        root: "/invoice/list",
        matcher: /^\/invoice\/list(\/|$)/,
        permissionKeys: ["invoices"],
      },
    ],
  },
  {
    type: "group",
    label: "Notifications",
    key: "notifications",
    matcher: /^\/notifications(\/|$)/,
    permissionKeys: ["notifications", "messages"],
    children: [
      {
        label: "Messages",
        root: "/notifications/messages",
        matcher: /^\/notifications\/messages(\/|$)/,
        permissionKeys: ["messages"],
      },
    ],
  },
  {
    type: "group",
    label: "Panelist",
    key: "panelist",
    matcher: /^\/(community-users|user-screening\/(?:questions|panel-survey))(\/|$)/,
    permissionKeys: ["community_users", "user_screening_management", "panel_survey"],
    children: [
      {
        label: "Panel List",
        root: "/community-users",
        isActive: matchesCommunityUsersMain,
        matcher: /^\/community-users(\/|$)/,
        permissionKeys: ["community_users"],
      },
      {
        label: "Panel Questionnaire",
        root: "/user-screening/questions",
        isActive: matchesUserScreeningQuestionsMain,
        matcher: /^\/user-screening\/questions(\/|$)/,
        permissionKeys: ["user_screening_management"],
      },
      {
        label: "Panel Survey",
        root: "/user-screening/panel-survey",
        isActive: matchesPanelSurveyMain,
        matcher: /^\/user-screening\/panel-survey(\/|$)/,
        permissionKeys: ["panel_survey"],
      },
      // Hidden from navigation — moved to System Email Template section
      // {
      //   label: "User Email Templates",
      //   root: "/user-email-templates",
      //   matcher: /^\/user-email-templates(\/|$)/,
      //   permissionKeys: ["user_email_templates"],
      // },
    ],
  },
  {
    type: "group",
    label: "Reward Points",
    key: "reward-points",
    matcher: /^\/reward-points(\/|$)/,
    permissionKeys: [
      "reward_points",
      "reward_history",
      "pending_rewards",
      "completed_rewards",
      "reward_settings",
    ],
    children: [
      {
        label: "Reward History",
        root: "/reward-points/history",
        matcher: /^\/reward-points\/history(\/|$)/,
        permissionKeys: [
          "reward_history",
          "pending_rewards",
          "completed_rewards",
          "reward_points",
        ],
      },
      {
        label: "Pending Rewards",
        root: "/reward-points/pending",
        matcher: /^\/reward-points\/pending(\/|$)/,
        permissionKeys: ["pending_rewards"],
      },
      {
        label: "Completed Rewards",
        root: "/reward-points/completed",
        matcher: /^\/reward-points\/completed(\/|$)/,
        permissionKeys: ["completed_rewards"],
      },
      {
        label: "Reward Settings",
        root: "/reward-points/settings",
        matcher: /^\/reward-points\/settings(\/|$)/,
        permissionKeys: [
          "reward_settings",
          "reward_points",
          "pending_rewards",
          "completed_rewards",
        ],
      },
    ],
  },
  {
    type: "link",
    label: "Home Page Management",
    root: "/home-page",
    matcher: /^\/home-page(\/|$)/,
    permissionKeys: ["homepage_management"],
  },
  {
    type: "group",
    label: "System Email Template",
    key: "system-email",
    matcher: /^\/(system-email|user-email-templates)(\/|$)/,
    permissionKeys: ["system_email_templates", "user_email_templates"],
    children: [
      {
        label: "System Email Template",
        root: "/system-email",
        matcher: /^\/system-email(\/|$)/,
        permissionKeys: ["system_email_templates"],
      },
      {
        label: "User Email Templates",
        root: "/user-email-templates",
        matcher: /^\/user-email-templates(\/|$)/,
        permissionKeys: ["user_email_templates"],
      },
    ],
  },
  {
    type: "link",
    label: "Log Activity",
    root: "/log-activity",
    matcher: /^\/log-activity(\/|$)/,
    permissionKeys: ["log_activity"],
  },
  {
    type: "link",
    label: "Settings",
    root: "/settings",
    matcher: /^\/settings(\/|$)/,
    permissionKeys: [],
  },
];
