import {
  matchesPrescreenMain,
  matchesSurveyMain,
} from "./sidebarNavUtils";

export const SIDEBAR_NAV_ITEMS = [
  {
    type: "link",
    label: "Dashboard",
    root: "/",
    matcher: /^\/($|dashboard)/,
    permissionKeys: ["dashboard"],
  },
  {
    type: "link",
    label: "Users",
    root: "/users",
    matcher: /^\/users(\/|$)/,
    permissionKeys: ["users"],
  },
  {
    type: "link",
    label: "Clients",
    root: "/clients",
    matcher: /^\/clients(\/|$)/,
    permissionKeys: ["clients"],
  },
  {
    type: "link",
    label: "Partners",
    root: "/partners",
    matcher: /^\/partners(\/|$)/,
    permissionKeys: ["partners"],
  },
  {
    type: "link",
    label: "Project Managers",
    root: "/project-managers",
    matcher: /^\/project-managers(\/|$)/,
    permissionKeys: ["project_managers"],
  },
  {
    type: "group",
    label: "Sales",
    key: "sales",
    matcher: /^\/sales(\/|$)/,
    permissionKeys: ["sales", "rfq", "sales_manager"],
    children: [
      {
        label: "RFQ",
        root: "/sales/rfq",
        matcher: /^\/sales\/rfq(\/|$)/,
        permissionKeys: ["rfq"],
      },
      {
        label: "Sales Manager",
        root: "/sales/sales-manager",
        matcher: /^\/sales\/sales-manager(\/|$)/,
        permissionKeys: ["sales_manager"],
      },
    ],
  },
  {
    type: "group",
    label: "Prescreen",
    key: "prescreen",
    matcher: /^\/prescreen(\/|$)/,
    permissionKeys: ["prescreen", "prescreen_group"],
    children: [
      {
        label: "Prescreen Group",
        root: "/prescreen/group",
        matcher: /^\/prescreen\/group(\/|$)/,
        permissionKeys: ["prescreen_group"],
      },
      {
        label: "Prescreen",
        root: "/prescreen",
        isActive: matchesPrescreenMain,
        matcher: /^\/prescreen(\/|$)/,
        permissionKeys: ["prescreen"],
      },
    ],
  },
  {
    type: "group",
    label: "Survey",
    key: "survey",
    matcher: /^\/survey(\/|$)/,
    permissionKeys: [
      "survey",
      "group_survey",
      "recontact_survey",
      "survey_settings",
    ],
    children: [
      {
        label: "Survey",
        root: "/survey",
        isActive: matchesSurveyMain,
        matcher: /^\/survey(\/|$)/,
        permissionKeys: ["survey"],
      },
      {
        label: "Group Survey",
        root: "/survey/group",
        matcher: /^\/survey\/group(\/|$)/,
        permissionKeys: ["group_survey"],
      },
      {
        label: "Recontact Survey",
        root: "/survey/recontact",
        matcher: /^\/survey\/recontact(\/|$)/,
        permissionKeys: ["recontact_survey"],
      },
      {
        label: "Survey Settings",
        root: "/survey/settings",
        matcher: /^\/survey\/settings(\/|$)/,
        permissionKeys: ["survey_settings"],
      },
    ],
  },
  {
    type: "group",
    label: "Invoice",
    key: "invoice",
    matcher: /^\/invoice(\/|$)/,
    permissionKeys: ["invoice", "invoice_settings", "invoices"],
    children: [
      {
        label: "Invoice Settings",
        root: "/invoice/settings",
        matcher: /^\/invoice\/settings(\/|$)/,
        permissionKeys: ["invoice_settings"],
      },
      {
        label: "Invoices",
        root: "/invoice/list",
        matcher: /^\/invoice\/list(\/|$)/,
        permissionKeys: ["invoices"],
      },
    ],
  },
  {
    type: "group",
    label: "Notifications",
    key: "notifications",
    matcher: /^\/notifications(\/|$)/,
    permissionKeys: ["notifications", "messages"],
    children: [
      {
        label: "Messages",
        root: "/notifications/messages",
        matcher: /^\/notifications\/messages(\/|$)/,
        permissionKeys: ["messages"],
      },
    ],
  },
  {
    type: "group",
    label: "Reward Points",
    key: "reward-points",
    matcher: /^\/reward-points(\/|$)/,
    permissionKeys: [
      "reward_points",
      "pending_rewards",
      "completed_rewards",
      "reward_settings",
    ],
    children: [
      {
        label: "Pending Rewards",
        root: "/reward-points/pending",
        matcher: /^\/reward-points\/pending(\/|$)/,
        permissionKeys: ["pending_rewards"],
      },
      {
        label: "Completed Rewards",
        root: "/reward-points/completed",
        matcher: /^\/reward-points\/completed(\/|$)/,
        permissionKeys: ["completed_rewards"],
      },
      {
        label: "Reward Settings",
        root: "/reward-points/settings",
        matcher: /^\/reward-points\/settings(\/|$)/,
        permissionKeys: ["reward_settings"],
      },
    ],
  },
  {
    type: "group",
    label: "Screening Management",
    key: "user-screening",
    matcher: /^\/user-screening(\/|$)/,
    permissionKeys: ["user_screening_management"],
    children: [
      {
        label: "List of All Questions",
        root: "/user-screening/questions",
        matcher: /^\/user-screening\/questions(\/|$)/,
        permissionKeys: ["user_screening_management"],
      },
    ],
  },
  {
    type: "link",
    label: "Home Page Management",
    root: "/home-page",
    matcher: /^\/home-page(\/|$)/,
    permissionKeys: ["homepage_management"],
  },
  {
    type: "link",
    label: "System Email Template",
    root: "/system-email",
    matcher: /^\/system-email(\/|$)/,
    permissionKeys: ["system_email_templates"],
  },
  {
    type: "link",
    label: "Log Activity",
    root: "/log-activity",
    matcher: /^\/log-activity(\/|$)/,
    permissionKeys: ["log_activity"],
  },
  {
    type: "link",
    label: "Settings",
    root: "/settings",
    matcher: /^\/settings(\/|$)/,
    permissionKeys: [],
  },
];
