/**
 * Assembles props passed into ModuleListingDataCells for one listing page.
 */
export function buildListingDataCellProps(ctx) {
  return {
    rowIdKey: ctx.rowIdKey,
    renderCheckboxCell: ctx.renderCheckboxCell,
    showStatus: ctx.showStatus,
    rfq: ctx.rfq,
    renderStatus: ctx.renderStatus,
    effectiveStatusAsText: ctx.effectiveStatusAsText,
    formatStatusDisplay: ctx.formatStatusDisplay,
    statusColumnClass: ctx.statusColumnClass,
    statusDropdownOptions: ctx.statusDropdownOptions,
    allowWrite: ctx.allowWrite,
    isDarkMode: ctx.isDarkMode,
    onStatusChange: ctx.onStatusChange,
    setInternalData: ctx.setInternalData,
    effectiveStatusToggle: ctx.effectiveStatusToggle,
    compactStatusColumn: ctx.compactStatusColumn,
    allowRead: ctx.allowRead,
    onView: ctx.onView,
    actionVariant: ctx.actionVariant,
    readOnlyListingActions: ctx.readOnlyListingActions,
    listingReadMode: ctx.listingReadMode,
    communityUser: ctx.communityUser,
    groupSurveyProjects: ctx.groupSurveyProjects,
    userMgmtActions: ctx.userMgmtActions,
    canShowEdit: ctx.canShowEdit,
    canShowDelete: ctx.canShowDelete,
    canShowManagePermissions: ctx.canShowManagePermissions,
    editPath: ctx.editPath,
    showDeleteAction: ctx.showDeleteAction,
    onEdit: ctx.onEdit,
    onDelete: ctx.onDelete,
    onManagePermissions: ctx.onManagePermissions,
    onFindUser: ctx.onFindUser,
    onUserSurveyData: ctx.onUserSurveyData,
    onSurveyClone: ctx.onSurveyClone,
    onProjectUrlInfo: ctx.onProjectUrlInfo,
    onClone: ctx.onClone,
    onCopy: ctx.onCopy,
    onPdfDownload: ctx.onPdfDownload,
    onApprove: ctx.onApprove,
    onReject: ctx.onReject,
    onAddProject: ctx.onAddProject,
    onListProjects: ctx.onListProjects,
    onAddLog: ctx.onAddLog,
    onViewLogs: ctx.onViewLogs,
    onRewardLog: ctx.onRewardLog,
    onResendEmail: ctx.onResendEmail,
    onDownload: ctx.onDownload,
    surveyActionLabels: ctx.surveyActionLabels,
    handleEdit: ctx.handleEdit,
    handleDeleteRequest: ctx.handleDeleteRequest,
    hasProfileImageColumn: ctx.hasProfileImageColumn,
    nameAsText: ctx.nameAsText,
    nowrapAllCells: ctx.nowrapAllCells,
    descriptionMaxLines: ctx.descriptionMaxLines,
  };
}
